run:
  timeout: '5m'

linters:
  enable:
    - 'errcheck'
    - 'govet'
    - 'staticcheck'
    - 'unused'
    - 'gosimple'
    - 'ineffassign'
    - 'typecheck'
    - 'misspell'
    - 'gocyclo'
    - 'revive'
    - 'gocritic'
    - 'nakedret'
    - 'prealloc'

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    rules:
      - name: 'unexported-return'
        disabled: true
      - name: 'receiver-naming'

issues:
  exclude-use-default: false
